export const mockQuestions = [
  "¿Cuál ha sido tu mayor fuente de energía o desafío hoy?",
  "¿Qué pequeño hábito te gustaría integrar mañana?",
  "¿Cómo calificarías tu nivel de desconexión personal?",
  "¿Qué intención le darás a tu bienestar en las próximas horas?",
  "¿Hay algo más que quieras agregar para tu reflexión final?",
  "¿Cómo describirías tu estado emocional predominante a lo largo del día?",
  "¿Qué momento del día de hoy sentiste que disfrutaste con mayor plenitud?",
  "¿Hubo alguna situación que drenara tu energía de forma inesperada?",
  "¿Qué hiciste hoy exclusivamente para cuidar de ti mismo/a?",
  "¿Cómo calificarías la calidad de tu descanso o sueño la noche anterior?",
  "¿Qué pensamiento recurrente o preocupación te gustaría soltar en este momento?",
  "¿Cuál fue el mayor acto de autocompasión o paciencia que tuviste contigo hoy?",
  "¿Cómo estuvo tu nivel de concentración y enfoque en tus actividades?",
  "¿Qué le agradeces a tu cuerpo por haber hecho por ti durante este día?",
  "¿Pudiste establecer límites saludables frente a las demandas de los demás hoy?",
  "¿Qué aspecto de tu entorno físico actual te aporta más paz o tranquilidad?",
  "¿Qué emoción o sentimiento te cuesta más aceptar en este momento de tu vida?",
  "¿De qué logro, por pequeño que parezca, te sientes orgulloso/a en este momento?",
  "¿Cómo fue tu relación con la tecnología y las pantallas durante el día?",
  "¿Qué actividad sencilla te recarga las pilas de forma inmediata?",
  "¿Hubo algún momento de conexión profunda con otra persona o contigo mismo/a?",
  "¿Qué te gustaría hacer diferente el día de mañana para sentirte más ligero/a?",
  "¿Cómo influyó tu alimentación o hidratación en tu bienestar físico hoy?",
  "¿Qué enseñanza te deja el reto más difícil que enfrentaste recientemente?",
  "¿Qué tanto permitiste que el estrés del exterior afectara tu paz interior?",
  "¿Qué frase o palabra resume mejor la energía con la que terminas el día?",
  "¿Qué necesidad personal tuya has estado postergando y deberías atender?",
  "¿Qué te hizo sonreír o sentir gratitud, incluso en medio de la rutina?",
  "¿Cómo te sientes respecto al ritmo que llevas en tu vida actualmente?",
  "¿Qué promesa o compromiso te gustaría hacerte a ti mismo/a para esta semana?",
];

export const TOTAL_QUESTIONS_TO_ASK = 10;
export const MIN_QUESTIONS_TO_ASK = 3;
